version: '3'
services:
  api:
    container_name: mooc-api
    build:
      context: docker/rust
      dockerfile: Dockerfile
    ports:
      - ${MOOC_API_PORT}:${MOOC_API_PORT}
    env_file:
      - .env
    volumes:
      - ./:/app/
