version: '3'
services:
  api:
    container_name: mooc-api
    build:
      context: docker/rust
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - ${MOOC_API_PORT}:${MOOC_API_PORT}
    env_file:
      - .env
    volumes:
      - ./:/app/
  db:
    container_name: mooc-db
    image: postgres:14-alpine
    ports:
      - ${MOOC_DB_PORT}:${MOOC_DB_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${MOOC_DB_USER}
      - POSTGRES_PASSWORD=${MOOC_DB_PASSWORD}
      - POSTGRES_DB=${MOOC_DB_DATABASE}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
