[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.3.3"
actix-cors = "0.5.4"
serde = "1.0"
serde_json = "1.0"
mooc-context = {path = "../mooc-context"}